JS-Ninjaaaa/RepoInterviewer

backend/README.md
backend/app/api/endpoints/health.py
backend/app/services/llm_client.py

やったこと
- LLMとの接続検証を ``health.py``に追加
- READMEをバックエンド向けに編集
- ``llm_client.py``でLLMとのやり取りを一部実装

add: health check for LLM connection

---

backend/app/api/endpoints/health.py
backend/app/api/endpoints/interview.py
backend/app/models/models.py
backend/app/services/llm_client.py
backend/main.py
backend/requirements.txt

Blackを導入してフォーマットを整えた
- Close #14

edited by Black

---

api.yml

- Close #19 
POST /interview/{interview_id} にて，
その質問に対する回答の点数も返すようにした．

fixed: api doc

---

backend/app/api/endpoints/interview.py
backend/app/repositories/production/redis_repo.py
backend/app/services/interview_service.py
backend/app/services/llm_service.py
backend/app/services/prompt_service.py

#45 
- API実装
- 総評プロンプトの開発
```
curl -L -X POST http://127.0.0.1:8000/interview \
-F "source_code=@file.zip" \
-F "difficulty=easy" \               
-F "total_question=5"
```
```
curl -X POST http://127.0.0.1:8000/interview/{interview_id} \
-H "Content-Type: application/json" \
-d '{
"question_id": 1,
"message": "少し難しいです"
}'
```
```
curl -X GET "http://127.0.0.1:8000/interview/{interview_id}/result"
```

総評とトータルスコアの取得，表示

---

frontend/src/commands/types/apiResponseValue.d.ts
frontend/src/webview/src/screens/GeneralFeedbackScreen.tsx
frontend/src/webview/src/types/apiResponseValue.d.ts

- Close #50 
https://github.com/user-attachments/assets/6995f480-5c5f-4e7a-a37f-ffe782b89b02

総評を表示できるようにした

---

backend/app/services/llm_service.py

- Close #57 
`llm_service.py` の `import` 文を修正した

質問数に応じて満点が正しく設定されるようにした

---

frontend/src/commands/functions/openWebview.ts

- Close #59 
・ セッションが途切れないようにpanelの設定を追加した
https://github.com/user-attachments/assets/7370b7c9-d237-4c28-9e9e-627f7a8c6bd4

セッションが途切れないように修正した

---

frontend/src/commands/functions/handleWebviewMessage.ts
frontend/src/commands/types/apiResponseValue.d.ts
frontend/src/webview/src/screens/AnswerScreen.tsx
frontend/src/webview/src/types/apiResponseValue.d.ts

APIレスポンスの変数名を変えた

---

api.yml
backend/app/api/endpoints/interview.py
backend/app/repositories/production/redis_repo.py
backend/app/schemas/schemas.py
backend/app/services/interview_service.py
backend/app/services/llm_service.py
backend/app/services/prompt_service.py

- Close #52
- 深掘り用のプロンプトテキストの追加
- API仕様書の変更（POSTのresponseにboolを追加した）
- 3回の深掘り質問に対応した
- 繋ぎ込んでみて

上級・激詰に対応させた

---

frontend/src/webview/src/screens/startScreen/StartScreen.tsx
frontend/src/webview/src/screens/startScreen/components/Header.tsx

- Close #72 
最初のページにヘッダーをつけた
https://github.com/user-attachments/assets/facc2a71-2e5a-4060-aad7-7b06d804ca7f

add header

---

backend/test_api.sh

```test_api.sh```の内容が古くなってたので一部更新

changed: sample zip file for test

---

backend/app/domain/entities/chat_history.py
backend/app/domain/entities/source_code.py
backend/app/domain/llm_clients/llm_client.py
backend/app/domain/repositories/interview_repository.py
backend/app/domain/repositories/source_code_repository.py

- Close #79 
- Close #88 
タイトル参照

RepositoryとLLMのインタフェースを定義した

---

frontend/src/commands/src/api/api.ts
frontend/src/commands/src/extension.ts
frontend/src/commands/src/functions/fetch-files.ts
frontend/src/commands/src/functions/handle-webview-message.ts
frontend/src/commands/tsconfig.json

- close #106 
commandsのtsconfigのビルドのrootDirをsrcにしたことで，ビルド成果物にsrcの階層がなくなった
どうさOK

fixed error

---

backend/app/domain/entities/chat_history.py
backend/app/domain/entities/evaluation_result.py
backend/app/domain/entities/interview_question.py
backend/app/domain/entities/source_code.py
backend/tests/usecase/test_set_up_interview_usecase.py

- Close #111 
タイトル参照
エンティティの属性を外部から変更できなくすることで堅牢性を高めるため
```
❯ pytest
======================================================= test session starts ========================================================
platform darwin -- Python 3.12.0, pytest-8.4.0, pluggy-1.6.0
rootdir: /Users/shunsei/workspace/project/hackathon/repo-interviewer/backend
configfile: pyproject.toml
plugins: anyio-4.9.0
collected 5 items                                                                                                                  
domain/entities/test_chat_history.py .                                                                                       [ 20%]
usecase/test_set_up_interview_usecase.py ....                                                                                [100%] …
```

エンティティーにgetterとsetterを追加した

---

.github/workflows/pr-test.yaml

#80 #114 
- pr時にテストが自動実行されるようにした
- mainにマージ後に、mainブランチのprotectionでこれが通らないとマージできないように設定する

CIワークフローを追加した

---

.github/workflows/notify-discord.yml

#113 
- PR作成と後からのアサインで通知が重複していたので消した

DiscordのPR通知の修正

---

.github/workflows/pr-test.yml

#118 
- 前回マージしたワークフローが正しく動かないことを手動実行で検証したので直した。
- 手動実行して動くことを確認
- 手動実行してみて
- 動いたら手動を消す

CIワークフローの修正

---

.github/workflows/notify-discord.yml

#113 
- 条件を追加して，コメント（start review)を押した際に動くようにした

Discord notifyがうるさいので改善した

---

backend/app/api/dependencies.py
backend/app/api/routers/interview.py
backend/app/schemas/interview_schema.py
backend/tests/api/routers/interview/test_get_question.py

- Close #154 
- タイトル参照
- 追加したrouterのテストコードを書いた
```sh
RepoInterviewer API Test CLI
--------------------------------
1. POST /interview
2. POST /interview/:interview_id
3. GET /interview/:interview_id?question_id=now
4. GET /interview/:interview_id?question_id=next
5. GET /interview/:interview_id/result
6. Exit
Select a test to run (1-6): 4
Testing GET /interview/:interview_id?question_id=2
Status: 200 ✅ Passed
Response: {"interview_id":"d13614a5-9660-4190-873e-0ad687fc5a1d","question_id":2,"question":"ranker.pyのcalculate_ranking関数で、同スコアのプレイヤーがいる場合のランキングってどうなってるか説明できる？バッチリ理解してたらマジすごいじゃん☆"}
```
```sh
================================================================ test session starts =================================================================
platform darwin -- Python 3.12.0, …
```

質問を取得するrouterを実装した

---

api.yml
backend/app/api/routers/interview.py
backend/app/usecase/usecases/get_question_usecase.py
backend/tests/api/routers/interview/test_get_question.py

- Close #122 
- タイトル参照
- GET `/interview/{interview_id} のレスポンスに404を追加した
- 追加したレスポンスのテストケースを追加した
テスト結果
```
❯ pytest
=========================================================================================== test session starts ============================================================================================
platform darwin -- Python 3.12.0, pytest-8.4.0, pluggy-1.6.0
rootdir: /Users/shunsei/workspace/project/hackathon/repo-interviewer/backend
configfile: pyproject.toml
plugins: anyio-4.9.0
collected 32 items                                                                                                                                                                                         
api/routers/interview/test_get_feedback.py .... …
```

OpenAPIを修正した

---

frontend/src/webview/src/App.tsx
frontend/src/webview/src/screens/title-screen/components/FeatureGrid.tsx
frontend/src/webview/src/screens/title-screen/components/TitleFooter.tsx
frontend/src/webview/src/screens/title-screen/components/TitleHeader.tsx

- Close # 169
UIの改善
・以前のコミットのバグ修正
・タイトルスクリーンのUI修正
before
after

タイトルスクリーンのUI を修正した
